# Generated by Django 5.2b1 on 2025-03-12 23:21

import core.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', core.fields.LowercaseEmailField(max_length=254, verbose_name='Email')),
                ('order_id', models.IntegerField(unique=True, verbose_name='ID заказа')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Пожертвование в промо-акцию',
                'verbose_name_plural': 'Пожертвование в промо-акции',
            },
        ),
    ]
