# Generated by Django 5.2b1 on 2025-11-22 21:01
from datetime import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_first_promo_action(apps, schema_editor):
    PromoAction = apps.get_model('donation', 'PromoAction')
    PromoDonation = apps.get_model('donation', 'PromoDonation')
    promo_action = PromoAction.objects.create(
        name='Выручаем каждый день 30.09.2025',
        created=datetime(2025, 9, 30, 0, 0, 1),
    )


def set_first_promo_action(apps, schema_editor):
    PromoAction = apps.get_model('donation', 'PromoAction')
    PromoDonation = apps.get_model('donation', 'PromoDonation')
    promo_action = PromoAction.objects.first()
    PromoDonation.objects.all().update(promo_action=promo_action)


class Migration(migrations.Migration):
    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=255, verbose_name='Название акции')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.AlterField(
            model_name='promodonation',
            name='order_id',
            field=models.IntegerField(verbose_name='ID заказа'),
        ),
        migrations.RunPython(create_first_promo_action, migrations.RunPython.noop),
        migrations.AddField(
            model_name='promodonation',
            name='promo_action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations',
                                    to='donation.promoaction', verbose_name='Акция'),
        ),
        migrations.AddConstraint(
            model_name='promodonation',
            constraint=models.UniqueConstraint(fields=('promo_action', 'order_id'),
                                               name='unique_order_per_promo_action'),
        ),
        migrations.RunPython(set_first_promo_action, migrations.RunPython.noop),
    ]
