# Generated by Django 5.2b1 on 2025-09-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_promoaction_promodonation_promo_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promodonation',
            name='order_id',
            field=models.IntegerField(verbose_name='ID заказа'),
        ),
        migrations.AddConstraint(
            model_name='promodonation',
            constraint=models.UniqueConstraint(fields=('promo_action', 'order_id'), name='unique_order_per_promo_action'),
        ),
    ]
